---
title: 'REDE SOCIAL DA TURMA'
subtitle: 'CDA010 - Visualização de Dados' 
author: 
  - 'Prof. Victor Valerio'
date: '_Última Atualização_: `r format(Sys.Date(), "%d de %B de %Y")`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, 
  fig.height=3.5, 
  fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE,
  fig.align = 'center'
)


```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
library(xaringanExtra)

style_duo_accent(
  primary_color = "#2F4F4F",
  secondary_color = "#EAD7B7",
  inverse_header_color = "#2B2B2B",
  text_font_size = '30px',
  header_h1_font_size = '3rem',
  header_h2_font_size = '2rem',
  header_h3_font_size = '1.5rem'
)

# RECURSOS DO SLIDE: ----
use_scribble()
use_search(show_icon = TRUE)
```

```{r import, message=FALSE, warning=FALSE, include=FALSE}
library(googlesheets4)

googlesheets4::gs4_auth(
  email = Sys.getenv("GOOGLE_EMAIL")
)

bd_bruto <- googlesheets4::read_sheet(
  ss = Sys.getenv("GOOGLE_SHEET_ID")
) %>% 
  janitor::clean_names()

colnames(bd_bruto) <- c('carimbo','votante',
                        'idade','genero',
                        'jeitinho','hierarquia',
                        'cotas','conservadorismo',
                        'indicado_01','indicado_02')

arestas <- bd_bruto %>%
  dplyr::select(votante, indicado_01, indicado_02) %>% 
  tidyr::pivot_longer(cols = -votante,
                      names_to = 'ordem',
                      values_to = 'indicado') %>% 
  dplyr::select(-ordem)

library(igraph)
library(ggplot2)
library(plotly)

grafico_rede <- ggraph(
  rede,
  layout = "fr"
) +
  geom_edge_link(
    alpha = 0.4
  ) +
  geom_node_point(
    size = 6
  ) +
  theme_void()

grafico <- plotly::ggplotly(grafico_rede)


```

```{r}
library(visNetwork)
library(igraph)

rede <- igraph::graph_from_data_frame(
  d = arestas,
  directed = TRUE,
)

nos <- data.frame(
  id = V(rede)$name,
  label = NA
)

arestas_vis <- igraph::as_data_frame(rede, what = "edges") |>
  dplyr::transmute(
    from = from,
    to = to
  )

visNetwork(nos, arestas_vis) |>
  visPhysics(stabilization = TRUE)
```


# APRESENTAÇÃO
----

- [**TÓPICO 01**](#topico_01)

- [**TÓPICO 02**](#topico_02)

- [**TÓPICO 03**](#topico_03)
